/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dbss079
 */
public class keluar extends javax.swing.JPanel {

    String p_id;
    String url = "jdbc:sqlserver://localhost:1433;databaseName=park;integratedSecurity=true";

    Calendar cal = Calendar.getInstance();
    Date date = cal.getTime();
    DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form keluar
     */
    public keluar(String p_id) {
        initComponents();
        this.p_id = p_id;
    }

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(10, 46, 90));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(10, 35, 66));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        input_plat = new javax.swing.JTextField();
        out_button = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 650));

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 233));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kendaraan Keluar");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 35, 66));
        jLabel2.setText("Plat Kendaraan");

        input_plat.setBackground(new java.awt.Color(240, 240, 240));
        input_plat.setBorder(null);
        input_plat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_platActionPerformed(evt);
            }
        });

        out_button.setBackground(new java.awt.Color(10, 35, 66));
        out_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                out_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                out_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                out_buttonMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Out");

        javax.swing.GroupLayout out_buttonLayout = new javax.swing.GroupLayout(out_button);
        out_button.setLayout(out_buttonLayout);
        out_buttonLayout.setHorizontalGroup(
            out_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, out_buttonLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(76, 76, 76))
        );
        out_buttonLayout.setVerticalGroup(
            out_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(out_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(input_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 182, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(out_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_plat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(out_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void input_platActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_platActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_platActionPerformed

    private void out_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_buttonMouseEntered
        setColor(out_button);
    }//GEN-LAST:event_out_buttonMouseEntered

    private void out_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_buttonMouseExited
        resetColor(out_button);
    }//GEN-LAST:event_out_buttonMouseExited

    private void out_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_buttonMousePressed
        String jam_keluar = timeFormat.format(date);
        String tanggal_operasi = dateFormat.format(date);

        try (Connection connection = DriverManager.getConnection(url);) {
            Statement stmt = connection.createStatement();
            String SQL = "EXECUTE setKendaraanKeluar '" + input_plat.getText() + "', '" + p_id + "', '" + jam_keluar + "', '" + tanggal_operasi + "'";
            ResultSet rs = stmt.executeQuery(SQL);
        } catch (SQLException e) {
        }
        biayaParkir(input_plat.getText());
        input_plat.setText("");
    }//GEN-LAST:event_out_buttonMousePressed

    public void biayaParkir(String plat) {
        String jamMasukStr = "", jamKeluarStr = "";
        int hargaParkir;

        try (Connection connection = DriverManager.getConnection(url);) {
            Statement stmt = connection.createStatement();
            String SQL = "EXECUTE getJam '" + plat + "'";
            ResultSet rs = stmt.executeQuery(SQL);

            while (rs.next()) {
                jamMasukStr = rs.getString("jam_masuk");
                jamKeluarStr = rs.getString("jam_keluar");
            }
        } catch (SQLException e) {
        }

        int jamMasuk = Integer.parseInt(jamMasukStr.substring(0, 2));
        int jamKeluar = Integer.parseInt(jamKeluarStr.substring(0, 2));
        int lama = (jamKeluar - jamMasuk) + 1;

        String jenis = cekJenis(plat);

        switch (jenis) {
            case "MOBIL":
                hargaParkir = lama * 5000;
                break;
            case "MOTOR":
                hargaParkir = lama * 3000;
                break;
            default:
                hargaParkir = 0;
        }
        JOptionPane.showMessageDialog(null, "Biaya parkir: Rp. " + hargaParkir);
    }
    
    public String cekJenis(String plat) {
        String jenis = "";
        try (Connection connection = DriverManager.getConnection(url);) {
            Statement stmt = connection.createStatement();
            String SQL = "SELECT jenis FROM riwayat_parkir WHERE plat='" + plat + "'";
            ResultSet rs = stmt.executeQuery(SQL);

            while (rs.next()) {
                jenis = rs.getString("jenis");
            }
        } catch (SQLException e) {
        }
        return jenis.toUpperCase();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_plat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel out_button;
    // End of variables declaration//GEN-END:variables
}
