/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.Color;
import javax.swing.JPanel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author dbss079
 */
public class masuk extends javax.swing.JPanel {

    String p_id;
    String jenis;
    String url = "jdbc:sqlserver://localhost:1433;databaseName=park;integratedSecurity=true";

    Calendar cal = Calendar.getInstance();
    Date date = cal.getTime();
    DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form kendaraan
     */
    public masuk(String p_id) {
        initComponents();
        this.p_id = p_id;
    }

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(10, 46, 90));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(10, 35, 66));

    }

    private void setColorDel(JPanel panel) {
        panel.setBackground(new Color(216, 93, 134));
    }

    private void resetColorDel(JPanel panel) {
        panel.setBackground(new Color(216, 30, 91));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        input_plat = new javax.swing.JTextField();
        select_mobil = new javax.swing.JRadioButton();
        select_motor = new javax.swing.JRadioButton();
        insert_button = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(760, 650));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kendaraan Masuk");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 35, 66));
        jLabel2.setText("Plat Kendaraan");

        input_plat.setBackground(new java.awt.Color(240, 240, 240));
        input_plat.setBorder(null);
        input_plat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_platActionPerformed(evt);
            }
        });

        select_mobil.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        select_mobil.setForeground(new java.awt.Color(10, 35, 66));
        select_mobil.setText("Mobil");
        select_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_mobilActionPerformed(evt);
            }
        });

        select_motor.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        select_motor.setForeground(new java.awt.Color(10, 35, 66));
        select_motor.setText("Motor");
        select_motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_motorActionPerformed(evt);
            }
        });

        insert_button.setBackground(new java.awt.Color(10, 35, 66));
        insert_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insert_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insert_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insert_buttonMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Insert");

        javax.swing.GroupLayout insert_buttonLayout = new javax.swing.GroupLayout(insert_button);
        insert_button.setLayout(insert_buttonLayout);
        insert_buttonLayout.setHorizontalGroup(
            insert_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insert_buttonLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(78, 78, 78))
        );
        insert_buttonLayout.setVerticalGroup(
            insert_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insert_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(input_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(select_mobil)
                        .addGap(18, 18, 18)
                        .addComponent(select_motor)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_plat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_mobil)
                    .addComponent(select_motor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void input_platActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_platActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_platActionPerformed

    private void select_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_mobilActionPerformed
        select_motor.setSelected(false);
        jenis = "Mobil";
    }//GEN-LAST:event_select_mobilActionPerformed

    private void select_motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_motorActionPerformed
        select_mobil.setSelected(false);
        jenis = "Motor";
    }//GEN-LAST:event_select_motorActionPerformed

    private void insert_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_buttonMouseEntered
        setColor(insert_button);
    }//GEN-LAST:event_insert_buttonMouseEntered

    private void insert_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_buttonMouseExited
        resetColor(insert_button);
    }//GEN-LAST:event_insert_buttonMouseExited

    private void insert_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_buttonMousePressed
        String jam_masuk = timeFormat.format(date);
        int id_park = 1;

        try (Connection connection = DriverManager.getConnection(url);) {
            Statement stmt = connection.createStatement();

            String SQL = "SELECT MAX(id_park) AS 'last_id' FROM data_parkir";
            ResultSet rs = stmt.executeQuery(SQL);

            while (rs.next()) {
                if (rs.getString("last_id") == null) {
                    id_park = 1;
                } else {
                    id_park = Integer.parseInt(rs.getString("last_id")) + 1;
                }
            }

            SQL = "EXECUTE setKendaraanMasuk '" + id_park + "', '" + input_plat.getText() + "', '" + jenis + "', '" + p_id + "', '" + jam_masuk + "'";
            rs = stmt.executeQuery(SQL);
        } catch (SQLException e) {
        }
        JOptionPane.showMessageDialog(null, "Input Berhasil");
        input_plat.setText("");
        select_mobil.setSelected(false);
        select_motor.setSelected(false);
    }//GEN-LAST:event_insert_buttonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_plat;
    private javax.swing.JPanel insert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton select_mobil;
    private javax.swing.JRadioButton select_motor;
    // End of variables declaration//GEN-END:variables
}
