package main;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import login.login_ok_park;
import panel.home;
import panel.masuk;
import panel.kendaraan;
import panel.keluar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dbss079
 */
public class main_ok_park extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    home home;
    keluar keluar;
    masuk masuk;
    kendaraan kendaraan;
    static String p_id;
    static String url = "jdbc:sqlserver://localhost:1433;databaseName=park;integratedSecurity=true";

    /**
     * Creates new form main_ok_park
     */
    public main_ok_park(String p_id) {
        initComponents();
        home = new home();
        keluar = new keluar(p_id);
        kendaraan = new kendaraan();
        masuk = new masuk(p_id);
        this.p_id = p_id;

        dynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        dynamicPanel.add(home, c);
        c.gridx = 0;
        c.gridy = 0;
        dynamicPanel.add(kendaraan, c);
        c.gridx = 0;
        c.gridy = 0;
        dynamicPanel.add(masuk, c);
        c.gridx = 0;
        c.gridy = 0;
        dynamicPanel.add(keluar, c);

        home.setVisible(true);
        kendaraan.setVisible(false);
        masuk.setVisible(false);
        keluar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        side_panel = new javax.swing.JPanel();
        home_button = new javax.swing.JPanel();
        s_home = new javax.swing.JPanel();
        home_label = new javax.swing.JLabel();
        kendaraan_button = new javax.swing.JPanel();
        s_kendaraan = new javax.swing.JPanel();
        home_label1 = new javax.swing.JLabel();
        masuk_button = new javax.swing.JPanel();
        s_masuk = new javax.swing.JPanel();
        home_label2 = new javax.swing.JLabel();
        keluar_button = new javax.swing.JPanel();
        s_keluar = new javax.swing.JPanel();
        home_label3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit_button = new javax.swing.JLabel();
        id_petugas = new javax.swing.JLabel();
        tglmasuk_petugas = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        nama_petugas = new javax.swing.JLabel();
        ttl_petugas = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dynamicPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1240, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_panel.setBackground(new java.awt.Color(68, 69, 69));
        side_panel.setForeground(new java.awt.Color(180, 1, 7));
        side_panel.setToolTipText("");
        side_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_button.setBackground(new java.awt.Color(162, 167, 165));
        home_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_buttonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_buttonMousePressed(evt);
            }
        });
        home_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s_home.setBackground(new java.awt.Color(218, 226, 223));

        javax.swing.GroupLayout s_homeLayout = new javax.swing.GroupLayout(s_home);
        s_home.setLayout(s_homeLayout);
        s_homeLayout.setHorizontalGroup(
            s_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        s_homeLayout.setVerticalGroup(
            s_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        home_button.add(s_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home_label.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        home_label.setForeground(new java.awt.Color(255, 255, 255));
        home_label.setText("Home");
        home_button.add(home_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 50));

        side_panel.add(home_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 164, -1));

        kendaraan_button.setBackground(new java.awt.Color(68, 69, 69));
        kendaraan_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kendaraan_buttonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kendaraan_buttonMousePressed(evt);
            }
        });
        kendaraan_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s_kendaraan.setBackground(new java.awt.Color(68, 69, 69));

        javax.swing.GroupLayout s_kendaraanLayout = new javax.swing.GroupLayout(s_kendaraan);
        s_kendaraan.setLayout(s_kendaraanLayout);
        s_kendaraanLayout.setHorizontalGroup(
            s_kendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        s_kendaraanLayout.setVerticalGroup(
            s_kendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        kendaraan_button.add(s_kendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home_label1.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        home_label1.setForeground(new java.awt.Color(255, 255, 255));
        home_label1.setText("Kendaraan");
        kendaraan_button.add(home_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 50));

        side_panel.add(kendaraan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 164, -1));

        masuk_button.setBackground(new java.awt.Color(68, 69, 69));
        masuk_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masuk_buttonMousePressed(evt);
            }
        });
        masuk_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s_masuk.setBackground(new java.awt.Color(68, 69, 69));

        javax.swing.GroupLayout s_masukLayout = new javax.swing.GroupLayout(s_masuk);
        s_masuk.setLayout(s_masukLayout);
        s_masukLayout.setHorizontalGroup(
            s_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        s_masukLayout.setVerticalGroup(
            s_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        masuk_button.add(s_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home_label2.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        home_label2.setForeground(new java.awt.Color(255, 255, 255));
        home_label2.setText("Masuk");
        masuk_button.add(home_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 50));

        side_panel.add(masuk_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 164, -1));

        keluar_button.setBackground(new java.awt.Color(68, 69, 69));
        keluar_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                keluar_buttonMousePressed(evt);
            }
        });
        keluar_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s_keluar.setBackground(new java.awt.Color(68, 69, 69));

        javax.swing.GroupLayout s_keluarLayout = new javax.swing.GroupLayout(s_keluar);
        s_keluar.setLayout(s_keluarLayout);
        s_keluarLayout.setHorizontalGroup(
            s_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        s_keluarLayout.setVerticalGroup(
            s_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        keluar_button.add(s_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home_label3.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        home_label3.setForeground(new java.awt.Color(255, 255, 255));
        home_label3.setText("Keluar");
        keluar_button.add(home_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 50));

        side_panel.add(keluar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 164, -1));

        logo.setFont(new java.awt.Font("Sugar Candy", 1, 30)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("OK - Park.");
        side_panel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 100));

        getContentPane().add(side_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(10, 93, 134));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Work\\Kuliah\\Harian\\Semester 3\\BasDat\\urgent.deploy.apps\\img.src\\user (2).png")); // NOI18N
        jLabel1.setAutoscrolls(true);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 90, 90));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 88, 90));

        exit_button.setIcon(new javax.swing.ImageIcon("D:\\Work\\Kuliah\\Harian\\Semester 3\\BasDat\\urgent.deploy.apps\\img.src\\exit.png")); // NOI18N
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit_buttonMousePressed(evt);
            }
        });
        jPanel5.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 50));

        id_petugas.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        id_petugas.setForeground(new java.awt.Color(255, 255, 255));
        id_petugas.setText("jLabel2");
        id_petugas.setName(""); // NOI18N
        jPanel5.add(id_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 210, -1));

        tglmasuk_petugas.setBackground(new java.awt.Color(255, 255, 255));
        tglmasuk_petugas.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tglmasuk_petugas.setForeground(new java.awt.Color(255, 255, 255));
        tglmasuk_petugas.setText("jLabel2");
        jPanel5.add(tglmasuk_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 87));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_petugas.setBackground(new java.awt.Color(255, 255, 255));
        nama_petugas.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        nama_petugas.setForeground(new java.awt.Color(255, 255, 255));
        nama_petugas.setText("jLabel2");
        jPanel7.add(nama_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 270, 30));

        ttl_petugas.setBackground(new java.awt.Color(255, 255, 255));
        ttl_petugas.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        ttl_petugas.setForeground(new java.awt.Color(255, 255, 255));
        ttl_petugas.setText("jLabel2");
        jPanel7.add(ttl_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 10));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 320, 670));

        jPanel2.setBackground(new java.awt.Color(10, 35, 66));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1080, 50));

        dynamicPanel.setBackground(new java.awt.Color(255, 255, 255));
        dynamicPanel.setForeground(new java.awt.Color(255, 255, 255));
        dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 760, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_home_buttonMouseEntered

    private void home_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_buttonMousePressed
        setColor(home_button, s_home);
        resetColor(kendaraan_button, s_kendaraan);
        resetColor(masuk_button, s_masuk);
        resetColor(keluar_button, s_keluar);

        home.setVisible(true);
        kendaraan.setVisible(false);
        masuk.setVisible(false);
        keluar.setVisible(false);
        home.refreshData();
    }//GEN-LAST:event_home_buttonMousePressed

    private void kendaraan_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraan_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_kendaraan_buttonMouseEntered

    private void kendaraan_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraan_buttonMousePressed
        resetColor(home_button, s_home);
        setColor(kendaraan_button, s_kendaraan);
        resetColor(masuk_button, s_masuk);
        resetColor(keluar_button, s_keluar);

        home.setVisible(false);
        kendaraan.setVisible(true);
        masuk.setVisible(false);
        keluar.setVisible(false);
        kendaraan.refreshData();
    }//GEN-LAST:event_kendaraan_buttonMousePressed

    private void masuk_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masuk_buttonMousePressed
        resetColor(home_button, s_home);
        resetColor(kendaraan_button, s_kendaraan);
        setColor(masuk_button, s_masuk);
        resetColor(keluar_button, s_keluar);

        home.setVisible(false);
        kendaraan.setVisible(false);
        masuk.setVisible(true);
        keluar.setVisible(false);
    }//GEN-LAST:event_masuk_buttonMousePressed

    private void keluar_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluar_buttonMousePressed
        resetColor(home_button, s_home);
        resetColor(kendaraan_button, s_kendaraan);
        resetColor(masuk_button, s_masuk);
        setColor(keluar_button, s_keluar);

        home.setVisible(false);
        kendaraan.setVisible(false);
        masuk.setVisible(false);
        keluar.setVisible(true);
    }//GEN-LAST:event_keluar_buttonMousePressed

    private void home_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_buttonMouseClicked
        
    }//GEN-LAST:event_home_buttonMouseClicked

    private void exit_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMousePressed
        String[] args = null;
        login_ok_park login = new login_ok_park();
        login.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_exit_buttonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_ok_park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_ok_park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_ok_park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_ok_park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        main_ok_park main = new main_ok_park(p_id);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.setVisible(true);
            }
        });
        main.isiDataPetugas(p_id);
    }

    public void isiDataPetugas(String p_id) {
        String nama = "", tempat_lahir = "", tgl_lahir = "", alamat = "", tgl_join = "";
        try (Connection connection = DriverManager.getConnection(url);) {
            Statement stmt = connection.createStatement();
            String SQL = "EXECUTE showDataPegawai '" + p_id + "'";
            ResultSet rs = stmt.executeQuery(SQL);

            while (rs.next()) {
                nama = rs.getString("nama");
                tempat_lahir = rs.getString("tempat_lahir");
                tgl_lahir = rs.getString("tgl_lahir");
                tgl_join = rs.getString("tgl_join");
            }
        } catch (SQLException e) {
        }
        nama_petugas.setText(nama);
        id_petugas.setText(p_id);
        tglmasuk_petugas.setText(tgl_join);
        ttl_petugas.setText(tgl_lahir);
    }

    private void setColor(JPanel panel, JPanel spanel) {
        panel.setBackground(new Color(162, 167, 165));
        spanel.setBackground(new Color(218, 226, 223));
    }

    private void resetColor(JPanel panel, JPanel spanel) {
        panel.setBackground(new Color(68, 69, 69));
        spanel.setBackground(new Color(68, 69, 69));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JLabel exit_button;
    private javax.swing.JPanel home_button;
    private javax.swing.JLabel home_label;
    private javax.swing.JLabel home_label1;
    private javax.swing.JLabel home_label2;
    private javax.swing.JLabel home_label3;
    private javax.swing.JLabel id_petugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel keluar_button;
    private javax.swing.JPanel kendaraan_button;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel masuk_button;
    private javax.swing.JLabel nama_petugas;
    private javax.swing.JPanel s_home;
    private javax.swing.JPanel s_keluar;
    private javax.swing.JPanel s_kendaraan;
    private javax.swing.JPanel s_masuk;
    private javax.swing.JPanel side_panel;
    private javax.swing.JLabel tglmasuk_petugas;
    private javax.swing.JLabel ttl_petugas;
    // End of variables declaration//GEN-END:variables
}
